### ISSUE TITLE
求告知快捷键调节亮度需要更改什么(教程细节或参考链接)，另提供MiniDP 4k方案

### ISSUE THREAD

**Issue by xqdd** [lyj0309/Hackintosh-CLEVO-H#2]
外接4K参考：
https://github.com/bufsnake/Z7-CT7NA-HackIntosh/issues/2#issuecomment-590061341

还有的话独立显卡是被屏蔽了的，所以MiniDP能外接的原因是他连的是核显，HDMI接口和USB 3.1 gen2 TypeC的DP连的都是独立显卡，所以不能外接任何显示器

**Comment by lyj0309** [comment]
直接在偏好设置里面调就好了的

**Comment by xqdd** [comment]
README.md看到
> 可使用 Fn+F11, Fn+F12 快捷键调节亮度

这个不行？

**Comment by xqdd** [comment]
经测试，F14（ScrollLock），F15（Pause）可调节（可爱的小太阳出现）
